feat/login screen ui/Diva 53 ui
assem16399/Diva pull request #3
Opened 2024-09-30 17:24 UTC by asmashawky

Jira Ticket : DIVA-53

> Description 

- login_ screen UI 
![photo_٢٠٢٤-٠٩-٣٠_١٩-٥٢-٥٩](https://github.com/user-attachments/assets/709a336b-6627-4540-a3b0-a3ce58d2d7e5)

2024-10-02 11:13 UTC, omarahmedx14 requested changes

2024-10-02 11:13 UTC, omarahmedx14 commented on lib/core/widgets/my_Text_Button.dart
> +class myTextButtom extends StatelessWidget {
please rename it to MyTextButtom

2024-10-02 11:13 UTC, omarahmedx14 commented on lib/core/widgets/my_Text_Feild.dart
> +class mytextfeild extends StatelessWidget {
please rename it to MyTextField

2024-10-02 11:13 UTC, omarahmedx14 commented on lib/features/login/ui/widgets/dont_Have_Account.dart
> +class dontHaveAccount extends StatelessWidget {
please rename it to DontHaveAccount

2024-10-03 00:04 UTC, asmashawky commented on lib/features/login/ui/widgets/dont_Have_Account.dart
> +class dontHaveAccount extends StatelessWidget {
RENAMED PLZ ACCEPT IT YA OMAR 🥹 🥹

2024-10-03 00:06 UTC, asmashawky commented on lib/core/widgets/my_Text_Feild.dart
> +class mytextfeild extends StatelessWidget {
RENAMED PLEEEEZ ACCEPT YA OMAR 👯

2024-10-03 00:06 UTC, asmashawky commented on lib/core/widgets/my_Text_Button.dart
> +class myTextButtom extends StatelessWidget {
RENAMED PLEEEEZ ACCEPT YA OMAR 🧛

2024-10-08 20:53 UTC, omarahmedx14 approved these changes

2024-10-09 17:02 UTC, merged