Feat/login/diva 55 login data
assem16399/Diva pull request #4
Opened 2024-10-01 03:36 UTC by asmashawky

## Jira Ticket: [DIVA-55](https://aasemhany.atlassian.net/browse/DIVA-55)

## Description 📖 

Implementing login Feature data layer (Models, ApiService, ApiRepo)

## How to Test 📋 
check the Signup Feature Data Layer folder

2024-10-02 11:14 UTC, omarahmedx14 requested changes

2024-10-02 11:14 UTC, omarahmedx14 commented on lib/core/widgets/my_Text_Button.dart
> +class myTextButtom extends StatelessWidget {
please rename myTextButtom

2024-10-02 11:14 UTC, omarahmedx14 commented on lib/core/widgets/my_Text_Feild.dart
> +class mytextfeild extends StatelessWidget {
here too

2024-10-02 11:14 UTC, omarahmedx14 commented on lib/features/login/ui/widgets/dont_Have_Account.dart
> +class dontHaveAccount extends StatelessWidget {
same

2024-10-03 00:07 UTC, asmashawky commented on lib/core/widgets/my_Text_Button.dart
> +class myTextButtom extends StatelessWidget {
RENAMED PLEEEEZ ACCEPT YA OMAR 🩻

2024-10-03 00:07 UTC, asmashawky commented on lib/core/widgets/my_Text_Feild.dart
> +class mytextfeild extends StatelessWidget {
AHOOH RENAMED PLEEEEZ ACCEPT YA OMAR 👍

2024-10-03 00:08 UTC, asmashawky commented on lib/features/login/ui/widgets/dont_Have_Account.dart
> +class dontHaveAccount extends StatelessWidget {
SM SM AHOWAT RENAMED PLEEEEZ ACCEPT YA OMAR 🌗

2024-10-05 01:11 UTC, closed without merging